services:
  - type: web
    name: pokemon-of-the-day
    runtime: ruby
    plan: free
    branch: main
    buildCommand: bash bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: WEB_CONCURRENCY
        value: "1"

